name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  php-syntax:
    name: PHP Syntax
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.2"
          - "8.5"
    steps:
      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          # This should be the value of the minimum PHP version as specified in composer.json
          php-version: ${{ matrix.php-version }}
          extensions: opcache
          coverage: none
          tools: none
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        name: Check PHP ${{ matrix.php-version }} syntax
        uses: mlocati/check-php-syntax@v1
        with:
          exclude: |
            .php-cs-fixer.php
            test

  php-cs:
    name: PHP Coding Style
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          tools: php-cs-fixer
          coverage: none
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        name: Run PHP-CS-Fixer
        run: php-cs-fixer check --ansi --no-interaction --using-cache=no --diff --show-progress=none --verbose


  phpunit:
    name: PHPUnit
    strategy:
      matrix:
        os:
          - ubuntu-latest
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        include:
          -
            os: windows-latest
            php-version: "7.2"
          -
            os: windows-latest
            php-version: "7.4"
          -
            os: windows-latest
            php-version: "8.5"
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          coverage: none
      -
        name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      -
        name: Install Composer dependencies
        run: composer --ansi --no-interaction --no-progress update
      -
        name: Run PHPUnit
        run:  composer --ansi --no-interaction run-script test -- -v
