name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  php-syntax:
    name: PHP Syntax
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          # This should be the value of the minimum PHP version as specified in composer.json
          php-version: 5.3
          extensions: opcache
          coverage: none
          tools: none
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Check syntax
        uses: mlocati/check-php-syntax@main
        with:
          exclude: |
            .php-cs-fixer.php

  php-cs:
    name: PHP Coding Style
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: php-cs-fixer
          coverage: none
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Run PHP-CS-Fixer
        run: php-cs-fixer check --ansi --no-interaction --using-cache=no --diff --show-progress=none
